# -*- coding: utf-8 -*-
"""
MTZ theme assembly — no template required.
Builds the icons zip and the final .mtz entirely in memory.
"""

import io
import zipfile

from PIL import Image, ImageDraw

from utils import log
from spec  import ALIASES

# ── Icon size for generated system assets ─────────────────────────────────────
_ICON_SIZE    = 192          # px — matches xxhdpi (96 dpi × 2)
_SCALE        = 0.80         # icon scaled to 80% of circle before compositing
_BG_COLOR     = (220, 220, 220, 255)   # light grey background  (#DCDCDC)

# ── transform_config.xml ──────────────────────────────────────────────────────
# Full 0→90 mapping: icons fill the entire cell (mask handles the clipping).
_TRANSFORM_CONFIG_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<IconTransform>
    <PointsMapping>
        <Point fromX="0.0" fromY="0.0"  toX="0.0"  toY="0.0"  />
        <Point fromX="0.0" fromY="90.0" toX="0.0"  toY="90.0" />
        <Point fromX="90.0" fromY="90.0" toX="90.0" toY="90.0" />
        <Point fromX="90.0" fromY="0.0" toX="90.0" toY="0.0"  />
    </PointsMapping>
</IconTransform>
"""


# ── System asset generators ───────────────────────────────────────────────────

def _make_circle_mask(size: int = _ICON_SIZE) -> bytes:
    """
    White circle on transparent background → icon_mask.png.
    HyperOS uses white pixels as the visible region.
    """
    img  = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.ellipse([0, 0, size - 1, size - 1], fill=(255, 255, 255, 255))
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


def _make_pattern(size: int = _ICON_SIZE) -> bytes:
    """
    Solid light-grey circle on transparent background → icon_pattern.png.
    Shown as background for unthemed icons.
    """
    img  = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    draw.ellipse([0, 0, size - 1, size - 1], fill=_BG_COLOR)
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


def _make_border(size: int = _ICON_SIZE) -> bytes:
    """
    Fully transparent PNG → icon_border.png.
    No decorative border; placeholder so HyperOS doesn't fall back to defaults.
    """
    img = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


def _circle_crop(png_bytes: bytes, size: int = _ICON_SIZE) -> bytes:
    """
    Composite a PNG onto a light-grey circle background:
      1. Draw solid grey circle
      2. Scale the source icon to (_SCALE × size), centred
      3. Paste with alpha mask → circular result

    Returns PNG bytes.
    """
    bg   = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(bg)
    draw.ellipse([0, 0, size - 1, size - 1], fill=_BG_COLOR)

    icon_size = int(size * _SCALE)
    offset    = (size - icon_size) // 2
    icon      = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    icon      = icon.resize((icon_size, icon_size), Image.LANCZOS)
    bg.paste(icon, (offset, offset), mask=icon)

    # Apply circular clip to the whole composite
    mask = Image.new("L", (size, size), 0)
    ImageDraw.Draw(mask).ellipse([0, 0, size - 1, size - 1], fill=255)
    bg.putalpha(mask)

    buf = io.BytesIO()
    bg.save(buf, "PNG")
    return buf.getvalue()


# ── description.xml ───────────────────────────────────────────────────────────

def make_description_xml(app_name: str) -> str:
    """Return a minimal HyperOS/MIUI-compatible description.xml string."""
    safe = (
        app_name
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        '<theme>\n'
        '<version><![CDATA[3.1]]></version>\n'
        '<uiVersion>17</uiVersion>\n'
        '<author><![CDATA[GitHub@C-F0x]]></author>\n'
        '<designer><![CDATA[GitHub@C-F0x]]></designer>\n'
        f'<title><![CDATA[{safe}]]></title>\n'
        '<description><![CDATA[Generated By GitHub@C-F0x\'s Theme Converter, '
        'plz dont distribute the mtz if the original icon pack is proprietary]]>'
        '</description>\n'
        '<miuiAdapterVersion>3.2</miuiAdapterVersion>\n'
        '</theme>\n'
    )


# ── Icons zip ─────────────────────────────────────────────────────────────────

def build_icons_zip(pkg_map: dict[str, str], pool: dict[str, bytes]) -> bytes:
    """
    Build the inner icons zip in memory.

    Structure:
      transform_config.xml
      res/drawable-xxhdpi/icon_mask.png
      res/drawable-xxhdpi/icon_pattern.png
      res/drawable-xxhdpi/icon_border.png
      res/drawable-xxhdpi/<package_name>.png   (raw, one per match)
      res/drawable-xxhdpi/<alias_target>.png   (copied from source per spec.py)

    Returns raw bytes.
    """
    buf = io.BytesIO()
    matched, missing = 0, []

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # System assets
        zf.writestr("transform_config.xml", _TRANSFORM_CONFIG_XML)
        zf.writestr("res/drawable-xxhdpi/icon_mask.png",    _make_circle_mask())
        zf.writestr("res/drawable-xxhdpi/icon_pattern.png", _make_pattern())
        zf.writestr("res/drawable-xxhdpi/icon_border.png",  _make_border())

        # Matched icons — written raw, no modification
        for pkg, drawable in pkg_map.items():
            png = pool.get(drawable)
            if png is None:
                missing.append(drawable)
                log.debug(f"MISS  {pkg} ← {drawable}.png")
            else:
                zf.writestr(f"res/drawable-xxhdpi/{pkg}.png", png)
                log.debug(f"OK    {pkg} ← {drawable}.png")
                matched += 1

        # Spec aliases — source is a package name; resolve via pkg_map → pool
        # Build a reverse map: package_name → png_bytes (already written icons)
        pkg_to_png: dict[str, bytes] = {
            pkg: pool[drawable]
            for pkg, drawable in pkg_map.items()
            if drawable in pool
        }

        alias_ok, alias_miss = 0, []
        for target, source_pkg in ALIASES.items():
            png = pkg_to_png.get(source_pkg)
            if png is None:
                alias_miss.append(f"{target} ← {source_pkg}")
                log.debug(f"ALIAS MISS  {target} ← {source_pkg} not in matched icons")
            else:
                zf.writestr(f"res/drawable-xxhdpi/{target}.png", png)
                log.debug(f"ALIAS OK    {target} ← {source_pkg}.png")
                alias_ok += 1

    total = len(pkg_map)
    pct   = matched / total * 100 if total else 0.0
    log.info(f"Icons: {matched}/{total} ({pct:.1f}%) matched, {len(missing)} missing")
    log.info(f"Aliases: {alias_ok}/{len(ALIASES)} applied"
             + (f", missing sources: {alias_miss}" if alias_miss else ""))
    print(f"\n  Matched:  {matched} / {total}  ({pct:.1f}%)")
    print(f"  Missing:  {len(missing)}  (details in process.log)")
    print(f"  Aliases:  {alias_ok} / {len(ALIASES)}")

    return buf.getvalue()


# ── MTZ assembly ──────────────────────────────────────────────────────────────

def build_mtz(
    app_name:    str,
    icons_bytes: bytes,
    previews:    dict[str, bytes],
) -> bytes:
    """
    Assemble the final .mtz zip entirely in memory (no template needed).

    Structure:
      description.xml
      icons                        ← the icons zip (stored as a raw entry)
      preview/<filename>.jpg  ×N   ← generated preview images

    Returns raw bytes.
    """
    buf = io.BytesIO()

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("description.xml", make_description_xml(app_name))
        zf.writestr("icons", icons_bytes)

        for fname, img_bytes in previews.items():
            zf.writestr(f"preview/{fname}", img_bytes)
            log.debug(f"MTZ: added preview/{fname} ({len(img_bytes):,} bytes)")

    log.info(f"MTZ assembled: {len(buf.getvalue()):,} bytes total")
    return buf.getvalue()